/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuthorPage: typeof import('./src/components/AuthorPage.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    GifsPage: typeof import('./src/components/GifsPage.vue')['default']
    HelloWorld: typeof import('./src/components/Dashboard.vue')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    LoaderCards: typeof import('./src/components/LoaderCards.vue')['default']
    NavbarHeader: typeof import('./src/components/Navbar-Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
